### PR TITLE
Fix issue reading floats and Network Interfaces

### LINKED ISSUE #71: Float and Network Interfaces are not being read correctly
### Describe the bug

When wanting to use the values from float or Network Interfaces, the values are stuck at their defaults.

### Steps to reproduce

1. Call `GetInterfaces`
2. Read any value from an interface
3. See only default values

### Expected behavior

The values are set to the values that the backend reports.

### Screenshots

None

### Cobbler version

````paste below
3.3.6
````

### Additional information

Found while updating the client on the terraform provider.

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #71 

This fixes two bugs (and extends a test case to cover this) that prevent setting float values and setting the correct values to Network Interfaces.

### CODE REVIEW

File: cobblerclient.go [hunk 1]
```diff
@@ -340,23 +344,25 @@ func cobblerDataHacks(fromType, targetType reflect.Kind, data interface{}) (inte
 			integerValue, err := convertToInt(data)
 			valueStruct.Data = integerValue
 			valueStruct.RawData = data
-			if err == nil {
+			if err != nil {
 				return Value[int]{}, err
 			}
 			return valueStruct, nil
+		case reflect.Float64:
+			// Int that may or may not be inherited
```
Comment (tiltingpenguin) [inline cobblerclient.go]: Nitpick: This is a float, not an int

**Review by tiltingpenguin — APPROVED** [review]
LGTM
