### PR TITLE
Testing: Compare XML instead of produces bytes

### LINKED ISSUE #69: Allow comparison of two XML files that send maps
### Describe the bug

Currently when having maps with content then they cannot be compared as the ordering is not stable.

### Steps to reproduce

1. Enable one of the skipped interface tests
2. See error

### Expected behavior

Tests shouldn't need to produce byte-identical XML files since they are logically identical.

### Screenshots

None

### Cobbler version

````paste below
Cobbler 3.3.6
  source: df356046f, Tue Jul 16 11:51:24 2024 +0200
  build time: Mon Sep 30 13:21:31 2024
````

### Additional information

None

### PR DESCRIPTION
**Pull request by SchoolGuy**
Fixes #69

### CODE REVIEW

**Review by tiltingpenguin — APPROVED** [review]
LGTM

**Comment by SchoolGuy** [comment]
This approach doesn't work at the moment since there is no concept of "map" available so it complains about unmatching elements.

File: testing.go [hunk 1]
```diff
@@ -133,3 +129,57 @@ func createStubHTTPClient(t *testing.T, fixtures []string) Client {
...
+type XMLRPCValue struct {
+	XMLType string
+	Int     int     `xml:"int"`
+	String  string  `xml:"string"`
+	Boolean bool    `xml:"boolean"`
+	Double  float64 `xml:"double"`
+	Base64  string  `xml:"base64"`
+	Struct  Struct  `xml:"struct"`
+	Array   Array   `xml:"array"`
+}
```
Comment (tiltingpenguin) [inline testing.go]: Nitpick: This can only hold one of the different types, right? I would like to at least make this clear with a comment

File: testing.go [hunk 2]
```diff
@@ -133,3 +129,57 @@ func createStubHTTPClient(t *testing.T, fixtures []string) Client {
...
+		}
+	}
+}
+
+type Member struct {
+	Name        string      `xml:"name"`
+	StructValue XMLRPCValue `xml:"value"`
+}
+
+type Struct struct {
```
Comment (tiltingpenguin) [inline testing.go]: I think Struct is a very poorly chosen name. Something that differentiates it more from the builtin struct would be good, even xmlrpcStruct, xmlrpcObject or -Response

File: testing.go (hunk 1 above)
Comment (SchoolGuy) [reply testing.go]: Comment is present now.

File: testing.go (hunk 2 above)
Comment (SchoolGuy) [reply testing.go]: I have renamed them to the same schema as the Value Struct.

File: testing.go [hunk 3]
```diff
@@ -133,3 +129,58 @@ func createStubHTTPClient(t *testing.T, fixtures []string) Client {
...
+	Base64  string       `xml:"base64"`
+	Struct  XMLRPCStruct `xml:"struct"`
+	Array   XMLRPCArray  `xml:"array"`
+}
+
+type Param struct {
+	Value XMLRPCValue `xml:"value"`
+}
+
+type MethodCall struct {
```
Comment (tiltingpenguin) [inline testing.go]: If you already prefix all these types with XMLRPC I would also do it here

**Review by tiltingpenguin — APPROVED** [review]
